name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # or change to your target branch

env:
  IMAGE_NAME: temmytope/student-tracker
  CONTAINER_NAME: student-tracker
  EC2_HOST: ubuntu@ec2-54-85-129-43.compute-1.amazonaws.com
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "SSH success!"
          whoami
          docker version
          docker pull $IMAGE_NAME
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME -p 8080:8000 $IMAGE_NAME
